version: "2"
services:
  db:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: studip_db
      MYSQL_USER: studip_user
      MYSQL_PASSWORD: studip_password
  web:
    image: studip/studip:latest
    depends_on:
      - db

    # Use port to redirect port
    # ports:
    #   - "8032:80"

    restart: always
    environment:
      MYSQL_DATABASE: studip_db
      MYSQL_USER: studip_user
      MYSQL_PASSWORD: studip_password
      MYSQL_HOST: db
      
      # Use automigrate to migrate your instance on startup
      # AUTO_MIGRATE: 1

      # Use proxy url if run behind a proxy
      #PROXY_URL: https://studip.example.com/

volumes:
  db_data: {}
