version: "2"
services:
  db:
    image: mariadb:10.4

    # The mysql volume has been deactivated to ensure that the database gets reinitialized every time
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: studip_db
      MYSQL_USER: studip_user
      MYSQL_PASSWORD: studip_password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  web:
    build:
      context: .
      args:

      # Modify branch to the svn branch you want to check out
        BRANCH: dev-branches/StEP00349
    depends_on:
      - db
    restart: always
    environment:
      MYSQL_DATABASE: studip_db
      MYSQL_USER: studip_user
      MYSQL_PASSWORD: studip_password
      MYSQL_HOST: db

      # Use proxy url if run behind a proxy
      #PROXY_URL: https://studip.example.com/

# Unquote
# volumes:
#   db_data: {}
